apiVersion: v1
kind: Route
metadata:
  name: ${project.artifactId}
spec:
  host: fruits-backend-services.apps.example.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: ${project.artifactId}